
#.
#Client-only settings - If you're looking for general settings, look inside your worlds serverconfig folder!
[client]

	#.
	#Configure your vision range when submerged in Create Henry's custom fluids
	[client.fluidFogSettings]
		#.
		#The vision range through sap will be multiplied by this factor
		#Range: 0.125 ~ 128.0
		sap_transparency = 1.0
		#.
		#Submerged fog color as a 24-bit RGB integer (e.g. 0xFF0000 = 16711680 = red). Requires restart.
		#Range: 0 ~ 16777215
		sap_fog_color = 14858276
		#.
		#The vision range through this milkshake will be multiplied by this factor
		#Range: 0.125 ~ 128.0
		chocolate_milkshake_transparency = 1.0
		#.
		#Submerged fog color as a 24-bit RGB integer (e.g. 0xFF0000 = 16711680 = red). Requires restart.
		#Range: 0 ~ 16777215
		chocolate_milkshake_fog_color = 9128495
		#.
		#The vision range through this milkshake will be multiplied by this factor
		#Range: 0.125 ~ 128.0
		vanilla_milkshake_transparency = 1.0
		#.
		#Submerged fog color as a 24-bit RGB integer (e.g. 0xFF0000 = 16711680 = red). Requires restart.
		#Range: 0 ~ 16777215
		vanilla_milkshake_fog_color = 16770979
		#.
		#The vision range through this milkshake will be multiplied by this factor
		#Range: 0.125 ~ 128.0
		strawberry_milkshake_transparency = 1.0
		#.
		#Submerged fog color as a 24-bit RGB integer (e.g. 0xFF0000 = 16711680 = red). Requires restart.
		#Range: 0 ~ 16777215
		strawberry_milkshake_fog_color = 16748465
		#.
		#The vision range through this milkshake will be multiplied by this factor
		#Range: 0.125 ~ 128.0
		glowberry_milkshake_transparency = 1.0
		#.
		#Submerged fog color as a 24-bit RGB integer (e.g. 0xFF0000 = 16711680 = red). Requires restart.
		#Range: 0 ~ 16777215
		glowberry_milkshake_fog_color = 16773222
		#.
		#The vision range through this milkshake will be multiplied by this factor
		#Range: 0.125 ~ 128.0
		pumpkin_milkshake_transparency = 1.0
		#.
		#Submerged fog color as a 24-bit RGB integer (e.g. 0xFF0000 = 16711680 = red). Requires restart.
		#Range: 0 ~ 16777215
		pumpkin_milkshake_fog_color = 16751164

