#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 20 15:02:15 PDT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.6
enableShaders=false
